# Generated by Django 2.2.6 on 2019-10-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='length',
            field=models.IntegerField(default=5),
        ),
    ]
