# Generated by Django 2.2.6 on 2019-12-09 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_quiz_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='text',
            new_name='ans_text',
        ),
    ]
